#!/bin/bash

# This script will check if a specified load balancer exist

# Get script directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Load configuration
source ${DIR}/aws.cnf

# Get region
if [[ -z $3 && -z $EC2_REGION ]]
then
  EC2_REGION="eu-west-1"
else
  if [[ -z $EC2_REGION ]]
  then
    EC2_REGION=$3
  fi
fi

# Get load balancer name
if [ -z $1 ]
then
  if [ $ELB_TRY_FIRST_LB ]
  then
    lb_name=`${AWS_ELB_HOME}/bin/elb-describe-lbs --region=${EC2_REGION} -C ${EC2_CERT} -K ${EC2_PRIVATE_KEY} | head -1 |  awk '{ print $2 }'`
  else
    echo "No Load Balancer name specified"
    # Exit unknown status
    exit 3
  fi
else
  lb_name=$1
fi

number_of_lb=`${AWS_ELB_HOME}/bin/elb-describe-lbs --region=${EC2_REGION} -C ${EC2_CERT} -K ${EC2_PRIVATE_KEY} $lb_name | wc -l`

# Nagios status are
# 0 - All is ok
# 1 - Warning
# 2 - Error
# 3 - unknown
return_status=3

if [ $number_of_lb -ge 1 ]
then
  return_status=0
  return_message="Load Balancer $lb_name exist"
else
  return_status=2
  return_message="Load Balancer $lb_name doesn't exist"
fi

echo $return_message
exit $return_status
