#!/bin/bash

# This script will check if the minimum number of desired instance is registred on specifed load balancer

# Get script directory
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Load configuration
source ${DIR}/ami.cnf

# Get minimum number of instance registred on load balancer desired
if [ -z $1 ]
then
  echo "You must specify number of desired registered instance on load balancer"
  exit 3
fi
min_instance_number=$1

# Get region
if [[ -z $3 && -z $EC2_REGION ]]
then
  EC2_REGION="eu-west-1"
else
  if [[ -z $EC2_REGION ]]
  then
    EC2_REGION=$3
  fi
fi

# Get load balancer name
if [ -z $2 ]
then
  if [ $ELB_TRY_FIRST_LB ]
  then
    lb_name=`${AWS_ELB_HOME}/bin/elb-describe-lbs --region=${EC2_REGION} | head -1 |  awk '{ print $2 }'`
  else
    echo "No Load Balancer name specified"
    # Exit unknown status
    exit 3
  fi
else
  lb_name=$2
fi


instance_running_number=`${EC2_HOME}/bin/elb-describe-instance-health ${lb_name} | grep InService | wc -l`


# Nagios status are
# 0 - All is ok
# 1 - Warning
# 2 - Error
# 3 - unknown
return_status=3

if [ $instance_running_number -ge $min_instance_number ]
then
  return_status=0
else
  return_status=2
fi
return_message="Number of running instance are $instance_running_number ($min_instance_number desired)"

echo $return_message
exit $return_status
